### ISSUE TITLE
A more accurare Dockerfile

### ISSUE THREAD

**Issue by thekoma** [pyed/transmission-telegram#25]
I've build a more featured Dockerfile / docker-compose.yml if you want to take a look.
[Koma-Andrea/docker-transmission-telegram](https://github.com/Koma-Andrea/docker-transmission-telegram)

Thank you for your code, is awesome.

**Comment by machsix** [comment]
No need for an additional entrypoint. The following works for me
```yaml
 version: "3"                                                                                                                                                                                                                                                 
 services:  
   telegram-transmission-bot:                                                                                                                                                                                                                                 
     container_name: telegram-transmission-bot                                                                                                                                                                                                                
     restart: on-failure                                                                                                                                                                                                                                      
     image: kevinhalpin/transmission-telegram:latest                                                                                                                                                                                                          
     environment:                                                                                                                                                                                                                                             
         - TELEGRAM_TRANSMISSION_BOT=foobar                                                                                                                                                                   
         - TELEGRAM_USERNAME=foobar                                                                                                                                                                                                                            
         - TRANSMISSION_URL=http://localhost:9092/transmission/rpc                                                                                                                                                                                           
         - USERNAME=foo                                                                                                                                                                                                                                    
         - PASS=bar                                                                                                                                                                                                                                    
     entrypoint: bash                                                                                                                                                                                                                                         
     command: ['-c', '/transmission-telegram -token=$${TELEGRAM_TRANSMISSION_BOT} -master=$${TELEGRAM_USERNAME} -url=$${TRANSMISSION_URL} -username=$${USERNAME} -password=$${PASS}']    
```
